apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-deployment
  namespace: chess
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: chess-backend
          image: codes0/chess:e6e25669ea49180608a38c139449cfadbfe4cf27
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: chess-backend-config



