apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-deployment
spec:
  replicas: 2
  selector:
    matchlebels: 
      app: chess-backend
  template:
    metadata:
      lebels:
        app: chess-backend
    spec:
      containers:
      - name: chess-container
        image: codes0/chess:e6e25669ea49180608a38c139449cfadbfe4cf27
        ports:
        - containerPort: 8080
        env:
          name: PORT
          valueFrom:
            configMapKeyRef:
              name: chess-backend-config
              key: PORT
        livenessProbe: 
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe: 
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5




